import { Injectable, Logger, OnApplicationBootstrap } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Atraccion } from '../entities/atraccion.entity';
import { Ciudad } from '../entities/ciudad.entity';
import { Operador } from '../entities/operador.entity';
import { ProductType } from '../dto/create-atraccion.dto';
import { CIUDADES_ECUADOR } from './ciudades.seed';

/**
 * Atracciones reales de Ecuador (2 por ciudad con aeropuerto) para el catálogo inicial.
 *
 * - Precios, horarios, coordenadas y operador: cada registro trae "fuentePrecio" y el
 *   detalle de fuentes está en CREDITOS_Y_FUENTES.md (misma carpeta). Investigado el 2026-10-05.
 * - Fotos: Wikimedia Commons, todas con licencia libre (CC0, CC BY, CC BY-SA o dominio público),
 *   verificadas con la API de Commons. Autor y licencia de cada foto en CREDITOS_Y_FUENTES.md.
 * - No se inventan puntuaciones ni reseñas: quedan en null / 0.
 *
 * Al arrancar la API inserta SOLO las atracciones cuyo nombre todavía no existe
 * (también cuenta las eliminadas, para no "revivir" lo que el operador borró).
 */
export const OPERADORES_SEED: Pick<Operador, 'id' | 'nombre'>[] = [
  { id: 1001, nombre: "Empresa Pública de Turismo Ciudad Mitad del Mundo EP" },
  { id: 1002, nombre: "TelefériQo" },
  { id: 1003, nombre: "Fundación Malecón 2000" },
  { id: 1004, nombre: "Acceso público (sin operador)" },
  { id: 1005, nombre: "ETAPA EP (Empresa Pública Municipal de Cuenca)" },
  { id: 1006, nombre: "Ministerio de Cultura y Patrimonio" },
  { id: 1007, nombre: "Rosita Tours (Puerto López)" },
  { id: 1008, nombre: "Ministerio del Ambiente, Agua y Transición Ecológica" },
  { id: 1009, nombre: "Yasuní Ecotour S.A." },
  { id: 1010, nombre: "MACCO EP (Gobierno Autónomo Descentralizado Municipal de Francisco de Orellana)" },
  { id: 1011, nombre: "Prefecturas de Loja y El Oro y municipios de Puyango y Las Lajas" },
  { id: 1012, nombre: "Fundación Charles Darwin" },
  { id: 1013, nombre: "Parque Nacional Galápagos" },
];

interface AtraccionSeed {
  nombre: string; ciudadId: number; descripcion: string; duracion: string; precio: number;
  tipo: keyof typeof ProductType; cancelacionGratuita: boolean; categorias: string[]; insignias: string[];
  incluye: string[]; idiomas: string[]; horarios: string[]; direccion: string; latitud: number; longitud: number;
  operadorId: number; fuentePrecio: string | null; fotos: string[];
}

export const ATRACCIONES_SEED: AtraccionSeed[] = [
  {"nombre": "Ciudad Mitad del Mundo", "ciudadId": 1, "descripcion": "Complejo turístico y cultural levantado junto a la línea equinoccial, en la parroquia de San Antonio de Pichincha, al norte de Quito. Su pieza central es el monumento de unos 30 metros dedicado a la Misión Geodésica Francesa, rodeado de museos, plazas y exhibiciones interactivas.", "duracion": "PT3H", "precio": 5.0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["cultura", "historia", "museo"], "insignias": [], "incluye": ["Ingreso al complejo Ciudad Mitad del Mundo"], "idiomas": ["es", "en"], "horarios": ["09:00", "11:00", "13:00", "15:00"], "direccion": "Av. Manuel Córdova Galarza S/N, San Antonio de Pichincha, Quito", "latitud": -0.00222, "longitud": -78.45583, "operadorId": 1001, "fuentePrecio": "https://mitaddelmundo.gob.ec/en/", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Mitad_del_Mundo%2C_Quito%2C_Ecuador%2C_2015-07-22%2C_DD_04.JPG/1280px-Mitad_del_Mundo%2C_Quito%2C_Ecuador%2C_2015-07-22%2C_DD_04.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Equator_Monument_Mitad_del_Mundo_Ecuador_DSC00138_ad.JPG/1280px-Equator_Monument_Mitad_del_Mundo_Ecuador_DSC00138_ad.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Mitad_del_Mundo%2C_Ecuador_2.jpg/1280px-Mitad_del_Mundo%2C_Ecuador_2.jpg"]},
  {"nombre": "TelefériQo", "ciudadId": 1, "descripcion": "Teleférico que sube desde las faldas occidentales de Quito hasta el sector de Cruz Loma, en las laderas del volcán Pichincha. En un trayecto de unos 18 minutos pasa de cerca de 3.100 a casi 3.950 metros de altura y ofrece vistas panorámicas de la ciudad y de los volcanes cercanos.", "duracion": "PT2H", "precio": 9.0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["mirador", "aventura", "naturaleza"], "insignias": [], "incluye": ["Ticket de góndola (tarifa extranjeros adultos)"], "idiomas": ["es", "en"], "horarios": ["10:00", "12:00", "14:00", "16:00"], "direccion": "Av. Occidental y Fulgencio Araujo, Quito 170527", "latitud": -0.19194, "longitud": -78.51889, "operadorId": 1002, "fuentePrecio": "https://teleferico.com.ec/preguntas-frecuentes/", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9b/Gondolas_of_the_TeleferiQo_in_Quito%2C_Ecuador.jpg/1280px-Gondolas_of_the_TeleferiQo_in_Quito%2C_Ecuador.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/Teleferico-volcan.jpg/1280px-Teleferico-volcan.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/Telef%C3%A9riQo_views_of_mountains_and_Quito_-_Ecuador_-_South_America.jpg/1280px-Telef%C3%A9riQo_views_of_mountains_and_Quito_-_Ecuador_-_South_America.jpg"]},
  {"nombre": "Malecón 2000", "ciudadId": 2, "descripcion": "Paseo regenerado de unos 2,5 km a orillas del río Guayas, en pleno centro de Guayaquil. Reúne jardines, monumentos como La Rotonda y la Torre Morisca, museos, restaurantes y zonas de juegos, y es uno de los espacios públicos más visitados de la ciudad.", "duracion": "PT2H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["cultura", "historia", "mirador"], "insignias": ["Entrada libre"], "incluye": ["Acceso libre al paseo"], "idiomas": ["es"], "horarios": ["08:00", "10:00", "16:00", "18:00"], "direccion": "Av. Simón Bolívar, junto al río Guayas, Guayaquil", "latitud": -2.194061, "longitud": -79.879874, "operadorId": 1003, "fuentePrecio": "https://www.goraymi.com/es-ec/guayas/guayaquil/malecones-muelles/malecon-2000-guayaquil-a27bfc049", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Vista_de_Malec%C3%B3n_2000%2C_Guayaquil%2C_Junio_de_2017.jpg/1280px-Vista_de_Malec%C3%B3n_2000%2C_Guayaquil%2C_Junio_de_2017.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Malec%C3%B3n_2000_en_Guayaquil.jpg/1280px-Malec%C3%B3n_2000_en_Guayaquil.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Vista_del_Malec%C3%B3n_2000.jpg/1280px-Vista_del_Malec%C3%B3n_2000.jpg"]},
  {"nombre": "Cerro Santa Ana y barrio Las Peñas", "ciudadId": 2, "descripcion": "Cerro histórico al norte del malecón donde nació Guayaquil, unido al tradicional barrio de Las Peñas. Una escalinata de 444 escalones, flanqueada por casas coloridas, cafés y galerías, lleva hasta una capilla y un faro desde cuya cima se domina la ciudad y el río Guayas.", "duracion": "PT2H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["historia", "mirador", "cultura"], "insignias": ["Entrada libre"], "incluye": ["Acceso libre a la escalinata, la capilla y el faro"], "idiomas": ["es"], "horarios": [], "direccion": "Cerro Santa Ana, barrio Las Peñas, Guayaquil", "latitud": -2.18088, "longitud": -79.875499, "operadorId": 1004, "fuentePrecio": "https://www.descubrecuador.com/item/faro-las-penas/", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Capilla_Santa_Ana_desde_el_Faro.JPG/1280px-Capilla_Santa_Ana_desde_el_Faro.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Abril_2005_029.jpg/1280px-Abril_2005_029.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Guayas_from_Santa_Ana.JPG/1280px-Guayas_from_Santa_Ana.JPG"]},
  {"nombre": "Parque Nacional Cajas", "ciudadId": 3, "descripcion": "Área protegida de páramo andino situada a unos 30 km al oeste de Cuenca, entre los 3.200 y 4.500 metros de altitud. Destaca por sus cientos de lagunas de origen glaciar, como la Toreadora, y por senderos de distinta dificultad entre bosques de polylepis.", "duracion": "PT4H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["naturaleza", "aventura", "vida silvestre"], "insignias": ["Entrada libre"], "incluye": ["Ingreso al parque con registro en el puesto de control"], "idiomas": ["es"], "horarios": ["08:00", "09:00", "10:00", "11:00"], "direccion": "Centro de visitantes Laguna Toreadora, km 32 vía Cuenca–Molleturo", "latitud": -2.846111, "longitud": -79.220276, "operadorId": 1005, "fuentePrecio": "https://cronicasargonauta.com/parque-nacional-cajas/", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/El_Cajas_National_Park_Laguna_Toreadora_in_rainy_weather_seen_from_the_viewpoint_1.jpg/1280px-El_Cajas_National_Park_Laguna_Toreadora_in_rainy_weather_seen_from_the_viewpoint_1.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Ama_la_Vida_-_Flickr_-_Laguna_La_Toreadora_Parque_Nacional_El_ajas_%288226328993%29.jpg/1280px-Ama_la_Vida_-_Flickr_-_Laguna_La_Toreadora_Parque_Nacional_El_ajas_%288226328993%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Ecuador_cajas_national_park.jpg/1280px-Ecuador_cajas_national_park.jpg"]},
  {"nombre": "Museo y Parque Arqueológico Pumapungo", "ciudadId": 3, "descripcion": "Complejo cultural del Ministerio de Cultura en el centro de Cuenca, levantado sobre los restos de un importante asentamiento inca. Combina salas de etnografía, arqueología y arte con un parque arqueológico de terrazas, jardines de plantas nativas y un centro de rescate de aves.", "duracion": "PT2H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["museo", "historia", "cultura"], "insignias": ["Entrada libre"], "incluye": ["Ingreso al museo y al parque arqueológico"], "idiomas": ["es"], "horarios": ["10:00", "12:00", "14:00"], "direccion": "Calle Larga y Av. Huayna Cápac, Cuenca", "latitud": -2.906139, "longitud": -78.996844, "operadorId": 1006, "fuentePrecio": "https://www.descubrecuador.com/item/museo-y-parque-arqueologico-pumapungo/", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/Cuenca_Pumapunku_seen_from_Avenida_Pumapungo.jpg/1280px-Cuenca_Pumapunku_seen_from_Avenida_Pumapungo.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/TEATRO_PUMAPUNGO_%2832097417774%29.jpg/1280px-TEATRO_PUMAPUNGO_%2832097417774%29.jpg"]},
  {"nombre": "Isla de la Plata (Parque Nacional Machalilla)", "ciudadId": 4, "descripcion": "Isla del Parque Nacional Machalilla ubicada a unos 40 km de Puerto López, conocida como la 'Galápagos de los pobres'. En ella anidan piqueros de patas azules y el albatros de Galápagos, y en sus aguas se practica esnórquel; entre junio y septiembre se suelen avistar ballenas jorobadas durante la travesía. Tarifa de referencia del operador: USD 45 por persona más USD 1 de muelle.", "duracion": "PT8H", "precio": 45.0, "tipo": "GUIDED_TOUR", "cancelacionGratuita": false, "categorias": ["vida silvestre", "naturaleza", "playa"], "insignias": ["Tour guiado"], "incluye": ["Traslado en yate desde Puerto López", "Guía en español e inglés", "Equipo de esnórquel", "Almuerzo"], "idiomas": ["es", "en"], "horarios": ["09:30"], "direccion": "Salida desde Puerto López, Manabí", "latitud": -1.27861, "longitud": -81.06861, "operadorId": 1007, "fuentePrecio": "https://www.rositatours.com/en/service-page/day-tour-isla-de-la-plata", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Isla_de_la_Plata_Ecuador448.JPG/1280px-Isla_de_la_Plata_Ecuador448.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/Isladelaplata.JPG/1280px-Isladelaplata.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Playa_Isla_de_Plata.JPG/1280px-Playa_Isla_de_Plata.JPG"]},
  {"nombre": "Playa El Murciélago", "ciudadId": 4, "descripcion": "Playa urbana de Manta, de alrededor de 1,7 km, cuyo nombre viene de la silueta de alas de murciélago que se aprecia desde el aire. Está bordeada por el Malecón Escénico, con restaurantes y espacios recreativos, y es popular para bañarse, practicar surf y deportes acuáticos.", "duracion": "PT3H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["playa", "aventura"], "insignias": ["Entrada libre"], "incluye": ["Acceso libre a la playa"], "idiomas": ["es"], "horarios": ["06:00", "09:00", "12:00"], "direccion": "Av. Malecón, junto al Malecón Escénico Murciélago, Manta", "latitud": -0.93745, "longitud": -80.729021, "operadorId": 1004, "fuentePrecio": "https://ec.viajandox.com/manta/playa-del-murcielago-A316", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Manta_Ecuador_playa_Murci%C3%A9lago_02.jpg/1280px-Manta_Ecuador_playa_Murci%C3%A9lago_02.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Ecuador_Manta_Murci%C3%A9lago_beach_01.jpg/1280px-Ecuador_Manta_Murci%C3%A9lago_beach_01.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/Manta_Ec_playa_Murci%C3%A9lago.jpg/1280px-Manta_Ec_playa_Murci%C3%A9lago.jpg"]},
  {"nombre": "Parque Nacional Podocarpus (sector Cajanuma)", "ciudadId": 5, "descripcion": "Parque nacional que protege bosques nublados y páramos entre Loja y Zamora Chinchipe, con una gran diversidad de aves y del árbol romerillo (Podocarpus). Su entrada principal, Cajanuma, queda a pocos minutos al sur de Loja y ofrece senderos cortos y rutas largas hacia las Lagunas del Compadre.", "duracion": "PT4H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["naturaleza", "vida silvestre", "aventura"], "insignias": ["Entrada libre"], "incluye": ["Ingreso al sector Cajanuma"], "idiomas": ["es"], "horarios": ["08:00", "09:00", "10:00", "11:00"], "direccion": "Sector Cajanuma, vía Loja–Vilcabamba (aprox. 8–15 km al sur de Loja)", "latitud": -4.28333, "longitud": -79.0, "operadorId": 1008, "fuentePrecio": "https://www.goraymi.com/es-ec/zamora-chinchipe/parques-nacionales/parque-nacional-podocarpus-alkaodann", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Podocarpus_Ecuador206.JPG/1280px-Podocarpus_Ecuador206.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Podocarpus_National_Park_%2814923333704%29.jpg/1280px-Podocarpus_National_Park_%2814923333704%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d8/Podocarpus_Ecuador209.JPG/1280px-Podocarpus_Ecuador209.JPG"]},
  {"nombre": "Vilcabamba, Valle de la Longevidad", "ciudadId": 5, "descripcion": "Parroquia rural de Loja situada a unos 45 km al sur de la ciudad, a cerca de 1.500 metros de altitud y con clima templado todo el año. Es conocida como el 'Valle de la Longevidad' y es punto de partida para caminatas como la del cerro Mandango, cabalgatas y visitas a cascadas.", "duracion": "PT8H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["naturaleza", "aventura", "cultura"], "insignias": ["Entrada libre"], "incluye": ["Visita libre al poblado"], "idiomas": ["es", "en"], "horarios": [], "direccion": "Parroquia Vilcabamba, cantón Loja", "latitud": -4.25583, "longitud": -79.21889, "operadorId": 1004, "fuentePrecio": "https://www.goraymi.com/es-ec/loja/loja/rurales/vilcabamba-turismo-ab5cf9e4b", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/Vilcabamba_Ecuador261.JPG/1280px-Vilcabamba_Ecuador261.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Vilcabamba_Ecuador_1302.jpg/1280px-Vilcabamba_Ecuador_1302.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Double_rainbow_Vilcabamba_Ecuador_1749.jpg/1280px-Double_rainbow_Vilcabamba_Ecuador_1749.jpg"]},
  {"nombre": "Parque Nacional Yasuní", "ciudadId": 6, "descripcion": "Una de las áreas protegidas más biodiversas del planeta, con más de 10.000 km² de selva amazónica, declarada Reserva de la Biosfera. Desde el Coca se llega en canoa por el río Napo para observar loros en saladeros, monos, aves y caminar por senderos de bosque primario. Tarifa de referencia del operador: USD 149 por persona con un mínimo de 3 pasajeros.", "duracion": "PT12H", "precio": 149.0, "tipo": "GUIDED_TOUR", "cancelacionGratuita": false, "categorias": ["naturaleza", "vida silvestre", "aventura"], "insignias": ["Tour guiado"], "incluye": ["Canoa Coca–Añangu–Coca", "Guía", "Entradas", "Refrigerio y almuerzo"], "idiomas": ["es"], "horarios": ["05:30"], "direccion": "Salida desde el muelle de Puerto Francisco de Orellana (Coca)", "latitud": -1.083, "longitud": -75.917, "operadorId": 1009, "fuentePrecio": "https://www.yasuniecotour.com/tienda/PARQUE-NACIONAL-YASUNI-Full-day-ANANGU-p569024096", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Many_parrots_-Anangu%2C_Yasuni_National_Park%2C_Ecuador_-clay_lick-8.jpg/1280px-Many_parrots_-Anangu%2C_Yasuni_National_Park%2C_Ecuador_-clay_lick-8.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Estacion_Cientifica_Yasuni_%28ECY%29_Yasuni_Research_Station.jpg/1280px-Estacion_Cientifica_Yasuni_%28ECY%29_Yasuni_Research_Station.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/Blue-throated_Piping_Guan_%28Pipile_cumanensis%29%2C_Yasuni_National_Park%2C_Ecuador.jpg/1280px-Blue-throated_Piping_Guan_%28Pipile_cumanensis%29%2C_Yasuni_National_Park%2C_Ecuador.jpg"]},
  {"nombre": "Museo Arqueológico y Centro Cultural de Orellana (MACCO)", "ciudadId": 6, "descripcion": "Museo ubicado en el malecón del Coca, frente al río Napo, dedicado al patrimonio de la Amazonía ecuatoriana. Exhibe más de 300 piezas arqueológicas de la fase Napo (1100–1500 d. C.), sobre todo cerámica policromada, y cuenta con biblioteca, sala de exposiciones temporales y auditorio.", "duracion": "PT1H30M", "precio": 5.0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["museo", "historia", "cultura"], "insignias": [], "incluye": ["Ingreso al museo (tarifa extranjeros)"], "idiomas": ["es"], "horarios": ["09:00", "11:00", "13:00", "15:00"], "direccion": "Av. 9 de Octubre y Eugenio Espejo, malecón del Coca", "latitud": -0.4742288, "longitud": -76.9851218, "operadorId": 1010, "fuentePrecio": "https://macco.ec/", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/5/51/Rio_Napo_in_Francisco_de_Orellana.jpg/1280px-Rio_Napo_in_Francisco_de_Orellana.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Puerto_Francisco_de_Orellana_01.jpg/1280px-Puerto_Francisco_de_Orellana_01.jpg"]},
  {"nombre": "Bosque Petrificado de Puyango", "ciudadId": 7, "descripcion": "Bosque protegido de unas 2.658 hectáreas en la cuenca del río Puyango, en el límite entre El Oro y Loja. Conserva troncos fosilizados de araucarias de alrededor de 100 millones de años, algunos de hasta 15 metros de largo, rodeados de bosque seco con más de 160 especies de aves.", "duracion": "PT2H", "precio": 1.0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["naturaleza", "historia", "vida silvestre"], "insignias": [], "incluye": ["Ingreso al bosque protegido"], "idiomas": ["es"], "horarios": ["08:00", "10:00", "12:00", "14:00"], "direccion": "Cuenca del río Puyango, límite entre los cantones Las Lajas/Arenillas (El Oro) y Puyango (Loja)", "latitud": -3.8824, "longitud": -80.0589, "operadorId": 1011, "fuentePrecio": "https://www.goraymi.com/es-ec/loja/puyango/bosques/bosque-petrificado-puyango-a530a1fd4", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/Bosque_Petrificado_de_Puyango603.jpg/1280px-Bosque_Petrificado_de_Puyango603.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Puyango_fossil_tree_02.JPG/1280px-Puyango_fossil_tree_02.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/39/Bosque_Petrificado_de_Puyango605.jpg/1280px-Bosque_Petrificado_de_Puyango605.jpg"]},
  {"nombre": "Archipiélago de Jambelí (Isla Jambelí)", "ciudadId": 7, "descripcion": "Conjunto de islas de manglar frente a la costa de El Oro, perteneciente en parte al cantón Santa Rosa. Su balneario principal, en la isla Jambelí, está a unos 35 minutos en lancha desde Puerto Bolívar y ofrece playa abierta al mar, restaurantes de mariscos y recorridos por los manglares. El pasaje en lancha desde Puerto Bolívar se paga aparte.", "duracion": "PT6H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["playa", "naturaleza"], "insignias": ["Entrada libre"], "incluye": ["Acceso libre a la playa (lancha no incluida)"], "idiomas": ["es"], "horarios": [], "direccion": "Isla Jambelí; embarque en el muelle de cabotaje de Puerto Bolívar", "latitud": -3.30848, "longitud": -80.06114, "operadorId": 1004, "fuentePrecio": null, "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Archipi%C3%A9lago_de_Jambel%C3%AD.jpg/1280px-Archipi%C3%A9lago_de_Jambel%C3%AD.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Mimus_longicaudatus%2C_Isla_Jambel%C3%AD%2C_Ecuador_1.jpg/1280px-Mimus_longicaudatus%2C_Isla_Jambel%C3%AD%2C_Ecuador_1.jpg"]},
  {"nombre": "Estación Científica Charles Darwin", "ciudadId": 8, "descripcion": "Centro de investigación de la Fundación Charles Darwin a orillas de la bahía Academia, en Puerto Ayora. Sus senderos y sala de exhibiciones explican la conservación de Galápagos y permiten ver de cerca tortugas gigantes e iguanas terrestres de los programas de crianza.", "duracion": "PT2H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["vida silvestre", "museo", "naturaleza"], "insignias": ["Entrada libre"], "incluye": ["Ingreso a la sala de exhibiciones"], "idiomas": ["es", "en"], "horarios": ["08:00", "10:00", "12:00", "14:00", "16:00"], "direccion": "Av. Charles Darwin s/n, Puerto Ayora, Santa Cruz", "latitud": -0.741944, "longitud": -90.304097, "operadorId": 1012, "fuentePrecio": "https://www.darwinfoundation.org/es/conocenos/nuestro-campus/visitor-center/", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Diego_at_the_Charles_Darwin_Research_Station_02.jpg/1280px-Diego_at_the_Charles_Darwin_Research_Station_02.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/Galapagos_tortoises_%28Chelonoidis_nigra_sp.%29_at_the_Charles_Darwin_Research_Station%2C_Santa_Cruz%2C_Galapagos_Islands_%287429209466%29.jpg/1280px-Galapagos_tortoises_%28Chelonoidis_nigra_sp.%29_at_the_Charles_Darwin_Research_Station%2C_Santa_Cruz%2C_Galapagos_Islands_%287429209466%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/064_SCruz_CDRS_Tortoises.jpg/1280px-064_SCruz_CDRS_Tortoises.jpg"]},
  {"nombre": "Bahía Tortuga (Tortuga Bay)", "ciudadId": 8, "descripcion": "Playa de arena blanca a unos 2,5 km de Puerto Ayora, a la que se llega por un sendero empedrado. Tiene un sector de oleaje fuerte apto para surf y otro de aguas calmas rodeado de manglar, donde se ven iguanas marinas, pelícanos y tiburones de punta blanca.", "duracion": "PT4H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["playa", "vida silvestre", "naturaleza"], "insignias": ["Entrada libre"], "incluye": ["Ingreso con registro en la caseta del Parque Nacional"], "idiomas": ["es", "en"], "horarios": ["06:00", "08:00", "10:00", "12:00", "14:00"], "direccion": "Inicio del sendero en la Av. Charles Binford, Puerto Ayora, Santa Cruz", "latitud": -0.76229485, "longitud": -90.3385311, "operadorId": 1013, "fuentePrecio": "https://happygringo.com/blog/tortuga-bay-galapagos/", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Tortuga_Bay%2C_beach_on_the_Island_of_Santa_Cruz.JPG/1280px-Tortuga_Bay%2C_beach_on_the_Island_of_Santa_Cruz.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Tortuga_Bay%2C_Galapagos_%2850135025612%29.jpg/1280px-Tortuga_Bay%2C_Galapagos_%2850135025612%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Marine_Iguana_%28Amblyrhynchus_cristatus%29_on_the_beach_at_Tortuga_Bay_-_Galapagos_-_Santa_Cruz_Island.JPG/1280px-Marine_Iguana_%28Amblyrhynchus_cristatus%29_on_the_beach_at_Tortuga_Bay_-_Galapagos_-_Santa_Cruz_Island.JPG"]},
  {"nombre": "Centro de Interpretación Gianni Arismendy", "ciudadId": 9, "descripcion": "Centro de interpretación ambiental en Puerto Baquerizo Moreno, inaugurado en 1994 con apoyo de la cooperación española. Sus tres salas recorren la historia natural de Galápagos, la llegada de los primeros pobladores y los retos de conservación, y desde allí parte el sendero al cerro Tijeretas.", "duracion": "PT1H30M", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["museo", "historia", "naturaleza"], "insignias": ["Entrada libre"], "incluye": ["Ingreso a las tres salas de exhibición"], "idiomas": ["es", "en"], "horarios": ["06:00", "08:00", "10:00", "12:00", "14:00", "16:00"], "direccion": "Av. Alsacio Northia, frente a Playa Mann, Puerto Baquerizo Moreno", "latitud": -0.89364526, "longitud": -89.60953831, "operadorId": 1013, "fuentePrecio": "https://ecuadorgalapagosinfo.com/turismo-en-galapagos/lugares-turisticos/cerro-tijeretas-centro-interpretacion-playa-punta-carola/", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/A_few_hours_ashore_at_Puerto_Baquerizo_Moreno_on_Isla_San_Cristobal_-_at_the_Park_museum_%2816689823202%29.jpg/1280px-A_few_hours_ashore_at_Puerto_Baquerizo_Moreno_on_Isla_San_Cristobal_-_at_the_Park_museum_%2816689823202%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6b/A_few_hours_ashore_at_Puerto_Baquerizo_Moreno_on_Isla_San_Cristobal_-_on_the_museum_grounds_-_%2816690856465%29.jpg/1280px-A_few_hours_ashore_at_Puerto_Baquerizo_Moreno_on_Isla_San_Cristobal_-_on_the_museum_grounds_-_%2816690856465%29.jpg"]},
  {"nombre": "Cerro Tijeretas", "ciudadId": 9, "descripcion": "Colina junto a Puerto Baquerizo Moreno a la que se llega por un sendero autoguiado de piedra que parte del Centro de Interpretación. Desde sus miradores se observan fragatas (tijeretas) y la bahía, y a sus pies hay una caleta donde se hace esnórquel con lobos marinos y tortugas.", "duracion": "PT2H", "precio": 0, "tipo": "SINGLE_TICKET", "cancelacionGratuita": true, "categorias": ["mirador", "vida silvestre", "naturaleza"], "insignias": ["Entrada libre"], "incluye": ["Sendero autoguiado y miradores"], "idiomas": ["es", "en"], "horarios": ["06:00", "08:00", "10:00", "12:00", "14:00"], "direccion": "Sendero desde el Centro de Interpretación, Puerto Baquerizo Moreno, San Cristóbal", "latitud": -0.88933, "longitud": -89.60675, "operadorId": 1013, "fuentePrecio": "https://ec.viajandox.com/san-cristobal/cerro-tijeretas-A98", "fotos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/Gal%C3%A1pagos_sea_lion_San_Crist%C3%B3bal_Gal%C3%A1pagos_Ecuador_DSC00189_ad.JPG/1280px-Gal%C3%A1pagos_sea_lion_San_Crist%C3%B3bal_Gal%C3%A1pagos_Ecuador_DSC00189_ad.JPG"]},
];

@Injectable()
export class AtraccionesSeed implements OnApplicationBootstrap {
  private readonly logger = new Logger(AtraccionesSeed.name);

  constructor(
    @InjectRepository(Atraccion) private readonly atracciones: Repository<Atraccion>,
    @InjectRepository(Ciudad) private readonly ciudades: Repository<Ciudad>,
    @InjectRepository(Operador) private readonly operadores: Repository<Operador>,
  ) {}

  async onApplicationBootstrap() {
    // Las ubicaciones dependen de las ciudades: se aseguran primero (no duplica nada).
    await this.ciudades.createQueryBuilder().insert().into(Ciudad).values(CIUDADES_ECUADOR).orIgnore().execute();
    await this.operadores.createQueryBuilder().insert().into(Operador).values(OPERADORES_SEED).orIgnore().execute();

    let nuevas = 0;
    for (const s of ATRACCIONES_SEED) {
      const existe = await this.atracciones.exists({ where: { nombre: s.nombre }, withDeleted: true });
      if (existe) continue;
      await this.atracciones.save(
        this.atracciones.create({
          nombre: s.nombre,
          descripcion: s.descripcion,
          duracion: s.duracion,
          precioTicket: s.precio,
          moneda: 'USD',
          tipoProducto: ProductType[s.tipo],
          cancelacionGratuita: s.cancelacionGratuita,
          categorias: s.categorias,
          insignias: s.insignias,
          incluye: s.incluye,
          idiomas: s.idiomas,
          horarios: s.horarios,
          cupoDiario: 20,
          puntuacion: null,
          numeroResenas: 0,
          estaActivo: true,
          operadorId: s.operadorId,
          ubicaciones: [{
            direccion: s.direccion, ciudadId: s.ciudadId, pais: 'ec',
            latitud: s.latitud, longitud: s.longitud, tipo: 'punto_de_encuentro',
          }] as any,
          fotos: s.fotos.map((url, orden) => ({ url, orden })) as any,
        }),
      );
      nuevas++;
    }
    this.logger.log(`Atracciones de ejemplo: ${ATRACCIONES_SEED.length} en el catálogo inicial (nuevas: ${nuevas})`);
  }
}
